### ISSUE TITLE
Launch SESMG v0.0.6

### ISSUE THREAD

**Issue by chrklemm** [chrklemm/SESMG#26]
All Changes have to be merged into a single branch:

- [x]  oemof 0.4 compatibility (#6) @GregorBecker 

- [x] Heat Pumps @janik257 

- [x] Non-Convex Investments (#7) @chrklemm 

- [x] Demo Feature @chrklemm 

In addition, a few facelifts must be carried out:

- [x] Restructuring of the Spreadsheet-scenario file @chrklemm, @janik257, @GregorBecker 

- [x] Heat Pump Documentation @janik257 

- [x] Update documentation due to the update to oemof 0.4 (min/max timeseries, fix timeseries, etc.) @GregorBecker 

- [x] Non-Convex Investment Documentation @chrklemm, 

- [x] Demo-Feature Documentation @chrklemm, @janik257

- [x] Correct errors in the documentation (#5, #22) @chrklemm, @janik257

- [x] Update linux and mac installation files (#4) @GregorBecker
